use super::*;

mod alien;
mod astronaut;
mod bear;
mod bird;
mod cactus;
mod cat;
mod coffee_cup;
mod cupcake;
mod diamond;
mod dog;
mod dragon;
mod fox;
mod frog;
mod ghost;
mod icecream;
mod knight;
mod monster;
mod mushroom;
mod ninja;
mod octopus;
mod panda;
mod paws;
mod penguin;
mod pizza;
mod planet;
mod robot;
mod rocket;
mod shield;
mod skull;
mod slime;
mod wizard;

pub(crate) use self::alien::*;
pub(crate) use self::astronaut::*;
pub(crate) use self::bear::*;
pub(crate) use self::bird::*;
pub(crate) use self::cactus::*;
pub(crate) use self::cat::*;
pub(crate) use self::coffee_cup::*;
pub(crate) use self::cupcake::*;
pub(crate) use self::diamond::*;
pub(crate) use self::dog::*;
pub(crate) use self::dragon::*;
pub(crate) use self::fox::*;
pub(crate) use self::frog::*;
pub(crate) use self::ghost::*;
pub(crate) use self::icecream::*;
pub(crate) use self::knight::*;
pub(crate) use self::monster::*;
pub(crate) use self::mushroom::*;
pub(crate) use self::ninja::*;
pub(crate) use self::octopus::*;
pub(crate) use self::panda::*;
pub(crate) use self::paws::*;
pub(crate) use self::penguin::*;
pub(crate) use self::pizza::*;
pub(crate) use self::planet::*;
pub(crate) use self::robot::*;
pub(crate) use self::rocket::*;
pub(crate) use self::shield::*;
pub(crate) use self::skull::*;
pub(crate) use self::slime::*;
pub(crate) use self::wizard::*;
